### ISSUE TITLE
microservices-recommendations  unable to build

### ISSUE THREAD

**Issue by basivireddy** [idugalic/micro-ecommerce#3]
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project microservices-recommendations: Could not resolve dependencies for project com.westum:microservices-recommendations:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.neo4j:neo4j-rest-graphdb:jar:2.0.1, org.neo4j:neo4j-cypher-dsl:jar:2.0.1: Failure to find org.neo4j:neo4j-rest-graphdb:jar:2.0.1 in https://repo.spring.io/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced -> [Help 1]

**Comment by dabeeru** [comment]
It seems that referenced version of one of dependencies has been removed from [official maven repository](https://mvnrepository.com/artifact/org.neo4j/neo4j-rest-graphdb/2.0.1)

You can resolve it by adding reference to neo4j maven repositories.

Add following into parent pom (/pom.xml):
```
<repositories>
(...)
    <repository>
        <id>neo4j-release-repository</id>
        <name>Neo4j Maven 2 release repository</name>
        <url>http://m2.neo4j.org/content/repositories/releases/</url>
    </repository>
(...)
</repositories>
```

**Comment by idugalic** [comment]
Thank you @dabeeru. Your fix is applied.

**Comment by crispr09** [comment]
this again stopped working
